version: '3.9'
services:
  db:
    image: mysql-db
    container_name: hackathon-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: hackathon-db
      MYSQL_USER: docker
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
  web:
    container_name: web
    build:
      dockerfile: ./Dockerfile
      context: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - ./.env